// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectTsnet(arg1:string):Promise<void>;

export function DisconnectTsnet():Promise<void>;

export function GetStatus():Promise<Record<string, any>>;
