// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportVideo(arg1) {
  return window['go']['main']['App']['ExportVideo'](arg1);
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function GetVideoServerURL() {
  return window['go']['main']['App']['GetVideoServerURL']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
