// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportVideo(arg1:main.ExportOptions):Promise<void>;

export function GetVideoInfo(arg1:string):Promise<main.VideoInfo>;

export function GetVideoServerURL():Promise<string>;

export function SelectFile():Promise<string>;
