// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectTsnet(arg1) {
  return window['go']['main']['App']['ConnectTsnet'](arg1);
}

export function DisconnectTsnet() {
  return window['go']['main']['App']['DisconnectTsnet']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}
