// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNow() {
  return window['go']['main']['ConnectionMonitor']['CheckNow']();
}

export function GetConnectionStatus() {
  return window['go']['main']['ConnectionMonitor']['GetConnectionStatus']();
}

export function Start(arg1) {
  return window['go']['main']['ConnectionMonitor']['Start'](arg1);
}
