// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWebSocket() {
  return window['go']['app']['ChatApp']['ConnectWebSocket']();
}

export function Disconnect() {
  return window['go']['app']['ChatApp']['Disconnect']();
}

export function GetMessages(arg1) {
  return window['go']['app']['ChatApp']['GetMessages'](arg1);
}

export function GetUsers() {
  return window['go']['app']['ChatApp']['GetUsers']();
}

export function RegisterUser(arg1) {
  return window['go']['app']['ChatApp']['RegisterUser'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['ChatApp']['SendMessage'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['ChatApp']['Startup'](arg1);
}
