// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerCall(arg1) {
  return window['go']['app']['ChatApp']['AnswerCall'](arg1);
}

export function CheckConnection() {
  return window['go']['app']['ChatApp']['CheckConnection']();
}

export function ConnectWebSocket() {
  return window['go']['app']['ChatApp']['ConnectWebSocket']();
}

export function CreateGroup(arg1, arg2, arg3) {
  return window['go']['app']['ChatApp']['CreateGroup'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['app']['ChatApp']['Disconnect']();
}

export function EndCall(arg1) {
  return window['go']['app']['ChatApp']['EndCall'](arg1);
}

export function GetGroupMessages(arg1) {
  return window['go']['app']['ChatApp']['GetGroupMessages'](arg1);
}

export function GetGroups() {
  return window['go']['app']['ChatApp']['GetGroups']();
}

export function GetMessages(arg1) {
  return window['go']['app']['ChatApp']['GetMessages'](arg1);
}

export function GetUserID() {
  return window['go']['app']['ChatApp']['GetUserID']();
}

export function GetUserName() {
  return window['go']['app']['ChatApp']['GetUserName']();
}

export function GetUsers() {
  return window['go']['app']['ChatApp']['GetUsers']();
}

export function InitiateCall(arg1, arg2) {
  return window['go']['app']['ChatApp']['InitiateCall'](arg1, arg2);
}

export function MarkAsRead(arg1, arg2) {
  return window['go']['app']['ChatApp']['MarkAsRead'](arg1, arg2);
}

export function RejectCall(arg1) {
  return window['go']['app']['ChatApp']['RejectCall'](arg1);
}

export function SendGroupMessage(arg1, arg2) {
  return window['go']['app']['ChatApp']['SendGroupMessage'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['ChatApp']['SendMessage'](arg1, arg2);
}

export function SendWebRTCSignal(arg1, arg2, arg3) {
  return window['go']['app']['ChatApp']['SendWebRTCSignal'](arg1, arg2, arg3);
}

export function SetUserName(arg1) {
  return window['go']['app']['ChatApp']['SetUserName'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['ChatApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['ChatApp']['Startup'](arg1);
}
