// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function ConnectWebSocket():Promise<void>;

export function Disconnect():Promise<void>;

export function GetMessages(arg1:string):Promise<Array<app.Message>>;

export function GetUsers():Promise<Array<app.User>>;

export function RegisterUser(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
