// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';
import {http} from '../models';

export function ExportVideo(arg1:app.ExportOptions):Promise<void>;

export function GetVideoInfo(arg1:string):Promise<app.VideoInfo>;

export function GetVideoServerURL():Promise<string>;

export function SelectFile():Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function VideoHandler(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
