// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportVideo(arg1) {
  return window['go']['app']['VideoEditorApp']['ExportVideo'](arg1);
}

export function GetLocalFileURL(arg1) {
  return window['go']['app']['VideoEditorApp']['GetLocalFileURL'](arg1);
}

export function GetVideoInfo(arg1) {
  return window['go']['app']['VideoEditorApp']['GetVideoInfo'](arg1);
}

export function GetVideoServerURL() {
  return window['go']['app']['VideoEditorApp']['GetVideoServerURL']();
}

export function SelectFile() {
  return window['go']['app']['VideoEditorApp']['SelectFile']();
}

export function Shutdown(arg1) {
  return window['go']['app']['VideoEditorApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['VideoEditorApp']['Startup'](arg1);
}

export function VideoHandler(arg1, arg2) {
  return window['go']['app']['VideoEditorApp']['VideoHandler'](arg1, arg2);
}
